<template>
  <div class="events-actions-info">
    <h3>Events and Actions Overview</h3>
    <p>
      This component displays the events that have occurred in the simulation
      and the actions that will be executed next. Events are the result of
      protocol operations, while actions are operations that will be executed
      when transitioning to the next simulation step. Actions that modify the
      trust graph or the network overlay are 'previewed' by the Simulation so
      you can directly see the impact of your changes in the gui, and can undo
      them before actually impacting the protocol.
    </p>

    <div class="section">
      <h4>Events</h4>
      <p>
        Events represent what has happened in the protocol during simulation.
        These include:
      </p>
      <ul>
        <li>
          <strong>Protocol Events</strong>: Events generated by the Federated
          Voting protocol itself, such as when a node votes, accepts a value, or
          confirms consensus.
        </li>
        <li>
          <strong>Overlay Events</strong>: Events related to the network
          overlay, such as nodes sending messages to each other.
        </li>
        <li>
          <strong>User Events</strong>: Events triggered by user actions, such
          as modifying trust configuration or network connections.
        </li>
      </ul>
    </div>

    <div class="section">
      <h4>Actions</h4>
      <p>
        Actions represent what will happen in the next simulation step. These
        include:
      </p>
      <ul>
        <li>
          <strong>Protocol Actions</strong>: Actions that the voting protocol
          will take next, such as broadcasting a vote or gossipping to
          neighbors.
        </li>
        <li>
          <strong>User Actions</strong>: Actions that were initiated by the user
          and will be executed next.
        </li>
      </ul>
      <p>
        <strong>Disrupting Actions</strong>: You can disrupt protocol actions to
        test how the protocol behaves under failure conditions. Disrupted
        actions are highlighted in red. A node that has a disrupted action will
        be marked as ill-behaved.
      </p>
    </div>
    <div class="section">
      <h4>Forge Messages</h4>
      In the bottom right corner you have the red envelope button. This button
      allows you to forge messages for a node. This can be used to test how the
      protocol reacts to malicious behavior.
    </div>
    <div class="section">
      <h4>Views</h4>
      <ul>
        <li>
          <strong>System View</strong>: Shows all events and actions in the
          system.
        </li>
        <li>
          <strong>Node View</strong>: When a node is selected, shows events and
          actions specifically related to that node.
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped>
.events-actions-info {
  padding: 1rem;
  line-height: 1.6;
}

.section {
  margin-bottom: 1.5rem;
}

h3 {
  font-size: 1.5rem;
  margin-bottom: 1rem;
  color: #2c3e50;
}

h4 {
  font-size: 1.1rem;
  margin-bottom: 0.75rem;
  color: #486581;
}

ul {
  padding-left: 1.5rem;
  margin-bottom: 1rem;
}

li {
  margin-bottom: 0.5rem;
}

strong {
  color: #334e68;
}
</style>
