//An action that is executed as a result of the protocol that is executed. For example send a message that
//is generated by the protocol. It allows the simulation to intercept these actions, log them, and give the user a

import { Context } from './Context';

//posibility to tamper with them (todo).
export abstract class ProtocolAction {
	public readonly type = 'ProtocolAction';
	abstract readonly subType: string;
	abstract readonly publicKey: string;
	abstract execute(context: Context): ProtocolAction[];
	abstract toString(): string;
}
