//An action that is executed as a result of the protocol that is executed. For example send a message that
//is generated by the protocol. It allows the simulation to intercept these actions, log them, and give the user a

import { Context } from './Context';

//todo rename ProtocolAction to OverlayActions? This is the only thing to be tampered with?
export abstract class ProtocolAction {
	public readonly type = 'ProtocolAction';
	abstract readonly subType: string;
	abstract readonly publicKey: string;
	isDisrupted: boolean = false;
	abstract execute(context: Context): ProtocolAction[];
	abstract toString(): string;
	abstract toJSON(): object;
}
