<template>
  <div class="controller-info">
    <h3>Simulation Overview</h3>
    <p>
      The federated voting simulation allows you to explore the behavior of the
      Federated Voting protocol under different conditions. You have the ability
      to cast votes, modify the trust configurations of every node and also the
      network overlay (the actual network connections between nodes).
    </p>
    <h4>System view and Node view</h4>
    <p>
      <strong>System view:</strong> By default you are shown the system view in
      the dashboard. This means you see the states of all the nodes in the
      network. For example you can directly observe which nodes transititioned
      to the accept phase.
    </p>
    <p>
      <strong>Node view:</strong> You can also inspect the state of a single,
      selected, node. States of other nodes will then depend on the messages
      that the selected node have received! For example if another node has
      transitioned to the accept phase, but the selected node has not received a
      message indicating this, it will not show this node as accepted.
    </p>
    <h4>Simulation Steps</h4>
    <p>
      The simulation is divided into <strong> simulation steps</strong>. Every
      step some actions are executed that advance the protocol. Which in turn
      can generate new actions. The advancements are captured through events
      that you can inspect in the event log or in the different available
      dashboard components.
    </p>
    <p>
      There are two kind of Actions: <strong>Protocol Actions</strong> and
      <strong>User Actions</strong>. Protocol Actions are generated by the
      protocol, while User Actions are generated by the user. User Actions can
      for example be an update of the network overlay or a change in the trust
      configuration of a node. Examples of protocol actions are a broadcast of a
      vote or gossiping of a vote to a nodes neigbors. You have the ability to
      disrupt the protocol actions, for example tamper with a broadcast, to see
      how the protocol reacts to such disruptions. To really test the protocol
      you also have the ability to create fake votes for a node.
    </p>

    <h4>Scenarios</h4>
    <p>
      The simulation provides interesting scenario's to explore. If you modify
      the simulation at any point, the scenario is abandoned and you actually
      start a new scenario that you can 'replay'. You can also export this
      scenario to share with others or to reuse later.
    </p>
    <h3>Simulation Controls and options</h3>
    <div class="section">
      <h4>Playback Controls</h4>
      <ul>
        <li>
          <strong>Back</strong> (⏪): Step backwards in the simulation to see
          previous states
        </li>
        <li>
          <strong>Play/Pause</strong> (▶/⏸): Automatically advance through
          simulation steps
        </li>
        <li>
          <strong>Forward</strong> (⏩): Move one step forward in the simulation
        </li>
        <li><strong>Stop/Reset</strong> (⏹): Stop/reset the simulation</li>
      </ul>
    </div>

    <div class="section">
      <h4>Keyboard Shortcuts</h4>
      <ul>
        <li><strong>n</strong>: Next step</li>
        <li><strong>shift-n</strong>: Previous step</li>
      </ul>
    </div>

    <div class="section">
      <h4>Scenario selector</h4>
      <p>Choose between different voting scenarios:</p>
      <ul>
        <li><strong>Consensus</strong>: Demonstrates successful consensus</li>
        <li>
          <strong>Stuck</strong>: Shows what happens when consensus cannot be
          reached
        </li>
        <li>
          Read about the different scenarios
          <a
            href="https://medium.com/stellarbeatio/federated-voting-part-3-scenarios-learn-about-a-stellar-consensus-protocol-scp-building-block-5f185485d772"
            >here</a
          >
        </li>
      </ul>
    </div>

    <div class="section">
      <h4>Scenario Options</h4>
      <p>You can customize and manage scenarios using the dropdown menu:</p>
      <ul>
        <li>
          <strong>Edit Settings</strong>: Configure network behavior:
          <ul>
            <li>
              Overlay: Fully connected - All nodes can directly communicate. If
              you disable this, you are in charge of setting up the network
              overlay/connections. For this you can use the overlay dashboard
              component.
            </li>
            <li>
              Overlay: Message Gossip - Messages propagate through the network.
              A node will send a message to its neighbors, which will then send
              it to their neighbors, and so on.
            </li>
          </ul>
        </li>
        <li>
          <strong>Export Scenario</strong>: Save your current scenario as JSON
          to share or reuse later
        </li>
        <li>
          <strong>Import Scenario</strong>: Load a previously exported scenario
          JSON
        </li>
        <li>
          <strong>Reset Scenario</strong>: Return the scenario to its initial
          state
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped>
.controller-info {
  padding: 1rem;
  line-height: 1.6;
}

.section {
  margin-bottom: 1.5rem;
}

h3 {
  font-size: 1.5rem;
  margin-bottom: 1rem;
  color: #2c3e50;
}

h4 {
  font-size: 1.1rem;
  margin-bottom: 0.75rem;
  color: #486581;
}

ul {
  padding-left: 1.5rem;
  margin-bottom: 1rem;
}

li {
  margin-bottom: 0.5rem;
}

strong {
  color: #334e68;
}
</style>
