name: Trunk-Based CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: radar_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: radar_test
      NODE_ENV: test
      DATABASE_TEST_URL: postgres://postgres:postgres@localhost:5432/radar_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
          run_install: false
      - name: Install dependencies
        run: |
          pnpm install
          pnpm build
      - name: Run tests
        run: pnpm tu

  terraform-unit-tests:
    name: 'Terraform Unit Tests'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init -backend=false

      # Validate terraform files
      - name: Terraform Validate
        run: terraform validate

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # Perform a security scan of the terraform code using checkov
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform

      # Upload results to GitHub Advanced Security
      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: checkov

  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
          run_install: false
      - name: Install dependencies
        run: |
          pnpm install
          pnpm build
      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy to Staging
        env:
          GITHUB_REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
          DOMAIN: ${{ secrets.STAGING_DOMAIN }}
        run: |
          doctl apps create --spec .do/app.staging.yaml
      - name: Wait for Staging Deployment
        run: |
          echo "Waiting for staging deployment to complete..."
          sleep 300
      - name: Run Staging Tests
        run: |
          # Add your staging environment tests here
          # For example, run API tests against staging endpoints
          echo "Running staging tests..."

  deploy-integration:
    needs: [test, deploy-staging]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
          run_install: false
      - name: Install dependencies
        run: |
          pnpm install
          pnpm build
      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy to Integration
        env:
          GITHUB_REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
          DOMAIN: ${{ secrets.INTEGRATION_DOMAIN }}
        run: |
          doctl apps create --spec .do/app.integration.yaml
      - name: Wait for Integration Deployment
        run: |
          echo "Waiting for integration deployment to complete..."
          sleep 300
      - name: Run Integration Tests
        run: |
          # Add your integration tests here
          echo "Running integration tests..."

  deploy-production:
    needs: [test, deploy-staging, deploy-integration]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
          run_install: false
      - name: Install dependencies
        run: |
          pnpm install
          pnpm build
      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy to Production
        env:
          GITHUB_REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
          DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
        run: |
          doctl apps create --spec .do/app.production.yaml
      - name: Wait for Production Deployment
        run: |
          echo "Waiting for production deployment to complete..."
          sleep 300
      - name: Run Production Smoke Tests
        run: |
          # Add your production smoke tests here
          echo "Running production smoke tests..."
